dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_script:
  - npm install

jobs:
  include:
    - stage: Test coverage
      script:
        - ng test --browsers=ChromeHeadlessNoSandbox --codeCoverage=true --watch=false
      after_script:
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi
